### ISSUE TITLE
用户首次注册后，系统记录的用户名不对。

### ISSUE THREAD

**Issue by shawnchain** [shawnchain/mclub-tracker-app#3]
系统生成的用户名：uXXXXYYYY
App在登录框的用户名缺少了个u

**Comment by lovekoala** [comment]
我本地跑服务端测试是正确的，因为之前手机已经在你的正式服务器上注册了，所以无法注册进行验证，你确定那个u不是你自己删掉的么。。。。。。确定的话再reopen吧。。。。。。
